`timescale 1ns / 1ps

module tb_jk_ff;

    reg  clk, rst, j, k;
    wire q;

    jk_ff uut (
        .clk(clk),
        .rst(rst),
        .j(j),
        .k(k),
        .q(q)
    );

    always #5 clk = ~clk;

    initial begin
        clk = 0; rst = 1; j = 0; k = 0;
        #10 rst = 0;

        #10 j = 1; k = 0;
        #10 j = 0; k = 1;
        #10 j = 1; k = 1;
        #10 j = 1; k = 1;
        #10 j = 0; k = 0;

        #20 $finish;
    end

    initial begin
        $monitor("Time=%0t | rst=%b j=%b k=%b | q=%b", $time, rst, j, k, q);
    end

endmodule
